#!/bin/env bash

source f.bash

if [ "$OSTYPE" == linux-gnu ]; then
  target=linux
  link_dir config ~/.config

elif [ "$OSTYPE" == darwin ]; then
  target=macos

fi

link_dir home ~
link_dir $target ~
link bin ~
