#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

  bspc monitor DP-0 -d I II III IV V
  bspc monitor HDMI-0 -d I II III IV V
# bspc monitor DVI-D-0 -d IV

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a map focus=off
